# Generated by Django 2.2.6 on 2019-10-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageInfoType',
            fields=[
                ('usage_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('usage_type_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_type_isvalid', models.BooleanField(default=True)),
                ('usage_type_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('usage_type_mod_date', models.DateTimeField(auto_now=True, verbose_name='mod_day')),
            ],
            options={
                'verbose_name_plural': '资产属性类型',
                'db_table': 'usage_info_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_info_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('usage_info_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_info.AssetBasicInfo')),
                ('usage_info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_usage.UsageInfoType')),
                ('usage_info_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '资产信息记录',
                'db_table': 'usage_info_',
                'managed': True,
            },
        ),
    ]
