# Generated by Django 2.2.6 on 2019-10-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_unit', '0002_auto_20191010_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBasicInfo',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_drx_asset_nr', models.BigIntegerField(blank=True, null=True)),
                ('item_drx_inventory_nr', models.BigIntegerField(blank=True, null=True)),
                ('item_pn_bcd', models.CharField(blank=True, max_length=45, null=True)),
                ('item_sn_bcd', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('item_sn_img', models.ImageField(blank=True, null=True, upload_to='asset_basic_sn')),
                ('item_contour_img', models.ImageField(blank=True, null=True, upload_to='asset_basic_contour')),
                ('item_sn_confirmed', models.BooleanField(default=False)),
                ('item_in_use', models.BooleanField(default=False)),
                ('item_is_fixed_asset', models.BooleanField(default=True)),
                ('item_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('item_mod_date', models.DateTimeField(auto_now=True, verbose_name='mod_day')),
                ('item_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_unit.CostCenter')),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '资产列表',
                'db_table': 'asset_basic_info',
                'managed': True,
            },
        ),
    ]
