# Generated by Django 2.2.6 on 2019-10-24 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产属性类型编码')),
                ('info_type_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产属性类型描述')),
                ('info_type_isvalid', models.BooleanField(default=True, verbose_name='资产属性有效')),
                ('info_type_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('info_type_mod_date', models.DateTimeField(auto_now=True, verbose_name='mod_day')),
            ],
            options={
                'verbose_name_plural': '资产属性类型',
                'db_table': 'finance_info_type',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='assetbasicinfo',
            old_name='item_in_use',
            new_name='item_available',
        ),
        migrations.RenameField(
            model_name='assetbasicinfo',
            old_name='item_cc',
            new_name='item_purchase_cc',
        ),
        migrations.RemoveField(
            model_name='assetbasicinfo',
            name='item_contour_img',
        ),
        migrations.RemoveField(
            model_name='assetbasicinfo',
            name='item_pn_bcd',
        ),
        migrations.RemoveField(
            model_name='assetbasicinfo',
            name='item_sn_bcd',
        ),
        migrations.RemoveField(
            model_name='assetbasicinfo',
            name='item_sn_confirmed',
        ),
        migrations.RemoveField(
            model_name='assetbasicinfo',
            name='item_sn_img',
        ),
        migrations.AddField(
            model_name='assetbasicinfo',
            name='item_po',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetPhysicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_info_pn_bcd', models.CharField(blank=True, help_text='Product #/Part #/Model/BM #', max_length=45, null=True, verbose_name='资产型号码')),
                ('physical_info_sn_bcd', models.CharField(blank=True, help_text='SN/serial number', max_length=45, null=True, unique=True, verbose_name='资产序列号')),
                ('physical_info_sn_img', models.ImageField(blank=True, help_text='清晰完整的SN照片', null=True, upload_to='img/asset_basic_sn', verbose_name='序列号照片')),
                ('physical_info_package_img', models.ImageField(blank=True, help_text='资产包装标签信息', null=True, upload_to='img/asset_basic_package', verbose_name='资产包装图')),
                ('physical_info_contour_img', models.ImageField(blank=True, help_text='清晰完整的外观照片', null=True, upload_to='img/asset_basic_contour', verbose_name='资产外观图')),
                ('physical_info_confirmed', models.BooleanField(default=False, verbose_name='资产信息财务确认状态')),
                ('physical_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('physical_info_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset_info.AssetBasicInfo')),
            ],
            options={
                'verbose_name_plural': '资产实物登记信息',
                'db_table': 'asset_physical_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetFinanceHistory',
            fields=[
                ('asset_finance_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_finance_history_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产信息描述')),
                ('asset_finance_history_add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add_day')),
                ('asset_finance_history_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_info.AssetBasicInfo', verbose_name='资产编号')),
                ('asset_finance_history_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_info.FinanceInfoType', verbose_name='信息类型')),
            ],
            options={
                'verbose_name_plural': '资产属性记录',
                'db_table': 'asset_finance_history',
                'managed': True,
            },
        ),
    ]
