# Generated by Django 2.2.6 on 2019-11-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_info', '0002_auto_20191024_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbasicinfo',
            name='item_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_unit.ManageGroup'),
        ),
        migrations.AlterField(
            model_name='assetphysicalinfo',
            name='physical_info_contour_img',
            field=models.ImageField(blank=True, help_text='清晰完整的外观照片', null=True, upload_to='img/asset_basic_contour/', verbose_name='资产外观图'),
        ),
        migrations.AlterField(
            model_name='assetphysicalinfo',
            name='physical_info_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset_info.AssetBasicInfo', verbose_name='资产DEC编号'),
        ),
        migrations.AlterField(
            model_name='assetphysicalinfo',
            name='physical_info_package_img',
            field=models.ImageField(blank=True, help_text='资产包装标签信息', null=True, upload_to='img/asset_basic_package/', verbose_name='资产包装图'),
        ),
        migrations.AlterField(
            model_name='assetphysicalinfo',
            name='physical_info_pn_bcd',
            field=models.CharField(blank=True, help_text='Product #/Part #/Model/BM #', max_length=45, null=True, verbose_name='资产型号'),
        ),
        migrations.AlterField(
            model_name='assetphysicalinfo',
            name='physical_info_sn_img',
            field=models.ImageField(blank=True, help_text='清晰完整的SN照片', null=True, upload_to='img/asset_basic_sn/', verbose_name='序列号照片'),
        ),
    ]
